# Generated by Django 4.1.3 on 2022-12-02 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('image', models.ImageField(upload_to='actors_directors/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Актеры и режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tagline', models.CharField(max_length=100, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movies/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выхода')),
                ('country', models.CharField(max_length=100, verbose_name='Страна выпуска')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name='Премьера в мире')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, help_text='в долларах', max_digits=12, verbose_name='Бюджет')),
                ('fees_usa', models.DecimalField(decimal_places=2, default=0.0, help_text='в долларах', max_digits=12, verbose_name='Сборы с США')),
                ('fees_world', models.DecimalField(decimal_places=2, default=0.0, help_text='в долларах', max_digits=12, verbose_name='Сборы в мире')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='movies_app.actordirector', verbose_name='Актеры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies_app.category', verbose_name='Категория')),
                ('directors', models.ManyToManyField(related_name='film_director', to='movies_app.actordirector', verbose_name='Режиссеры')),
                ('genres', models.ManyToManyField(to='movies_app.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie', verbose_name='Фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies_app.reviews')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='MovieCadres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='cadres_movies/', verbose_name='Изображение')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Кадр',
                'verbose_name_plural': 'Кадры',
            },
        ),
    ]
